# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: markupboy/node-aws:0.0.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm
      - run:
          name: Run tests
          command: npm run test

  build-and-deploy:
    docker:
      - image: markupboy/node-aws:0.0.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: |
            aws s3 sync build/ s3://circle-ic/ --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
            aws s3 sync build/ s3://circle-ic/ --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
  build-and-deploy:
    jobs:
      - test
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
